build: add missing gio-unix-2.0 dependency
Fixes

../src/gmw-main.c:25:10: fatal error: gio/gunixfdlist.h: No such file or directory
 #include <gio/gunixfdlist.h>
          ^~~~~~~~~~~~~~~~~~~